// <auto-generated />
using System;
using CalculadoraLaboralBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CalculadoraLaboralBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210605132230_i")]
    partial class i
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CalculadoraLaboralBackend.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidadDeHoras")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaDeFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaDeInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("horaDeFinalizacion")
                        .HasColumnType("int");

                    b.Property<int>("horaDeInicio")
                        .HasColumnType("int");

                    b.Property<int>("semanaDelAno")
                        .HasColumnType("int");

                    b.Property<string>("servicioRealizado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tecnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoDeHora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servicio");
                });
#pragma warning restore 612, 618
        }
    }
}
